version: "3.7"

services:

  flask:
    build: ./flask
    container_name: container-flask-develop
    restart: always
    environment:
      - APP_NAME=DevFlaskApp
    ports:
      - "80:80"
    # Share source code between the running container
    volumes: ['./flask:/app']
    # expose:
    #   - 8080

  # nginx:
  #   build: ./nginx
  #   container_name: nginx
  #   restart: always
  #   ports:
  #     - "80:80"